### ISSUE TITLE
On newer versions of windows the debug script isnn't working

### ISSUE THREAD

**Issue by Fefedu973** [8LWXpg/PowerToysRun-PluginTemplate#1]
On newer versions of windows the debug script isnn't working and i think it is due to the sudo command. I always get this error. 

```error: unexpected argument '-e' found    tip: to pass '-e' as a value, use '-- -e'  Usage: sudo.exe [OPTIONS] [COMMANDLINE]... [COMMAND]  For more information, try 'help'.```

If i run this script as admin having removed the sudo line irt works perfeclty

**Comment by 8LWXpg** [comment]
The script uses `gsudo`, you need to modify the script if you're using other sudo commands.
https://github.com/8LWXpg/PowerToysRun-PluginTemplate/blob/898ed204dc24db52ca9059a5d6ffe1b7aa1c736a/debug.ps1#L1
