### ISSUE TITLE
Unable to get template to build using existing readme steps

### ISSUE THREAD

**Issue by neilenns** [8LWXpg/PowerToysRun-PluginTemplate#3]
I'm taking the template for a spin and trying to get it to build without making any changes to the code. Here are the issues I've hit along the way:

1. The PowerShell scripts depend on `gsudo`, which I didn't have installed. I only discovered the requirement by reading the scripts. It should be listed as a warning or something in the readme.
2. Running `./copyLib.ps1` resulted in file doesn't exist error for each of the DLLs. It's trying to copy from `C:\Program Files\PowerToys\PowerToys.Common.UI.dll`. I don't have that folder on my machine.

I got myself unstuck on the first one, but am still stuck on the second trying to find where those DLLs are actually located on my computer.

**Comment by neilenns** [comment]
In the end I gave up on the template and used the one referenced in #2. That got me with something I could build and run, but then I hit a wall trying to get up in the debugger. I can attach correctly, but none of my breakpoints resolve. This isn't terribly surprising since I'm trying to mix a template from one approach with debug instructions from another, but still.., I was hopeful it would work 😅

**Comment by 8LWXpg** [comment]
If your PowerToys is install with user scope, you need to change `$ptPath` to your PowerToys install location manually:

https://github.com/8LWXpg/PowerToysRun-PluginTemplate/blob/b373ffcebe0876658341cf97d8076bd888c1c2eb/copyLib.ps1#L6-L18

There's indeed some information missing in the document, I'll try to clarify in `README`.

**Comment by neilenns** [comment]
Instead of the setup script, maybe update the template to use `Community.PowerToys.Run.Plugin.Dependencies`? Simply adding that to the project will result in the necessary support DLLs being available.
