### ISSUE TITLE
Missing copyLib.ps1

### ISSUE THREAD

**Issue by SamErde** [8LWXpg/PowerToysRun-PluginTemplate#4]
The readme mentions using **copyLib.ps1** but that file does not seem to exist.

**Comment by 8LWXpg** [comment]
We switched to `Community.PowerToys.Run.Plugin.Dependencies` nuget package at [v1.2.0](Community.PowerToys.Run.Plugin.Dependencies), so the copy dependency section in readme is redundant.

I'll update the readme and push a new release with updated documentation.
